language: java
jdk:
- oraclejdk8
script:
- ./gradlew shadowJar
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: "VqmLcwNKsTWNNDLqkZIbYy7c1Vl0ccXMdkiXQ+fF0aa1/bGvSBVNt49AKuYJvXPWgA/i7QXQmUNBls2qmC1Ib3GZqqNmksQSZCYyrEyMrPtHSjggcgrmSJ+nb65gzoreI1RQgq9PHd9PToMRINR1SvZbnjngqn8XmIAN6uN/m+RZQCxsA0K0/yIdDH0imWpKqGq6b/gcehhcKswNtuQVp+LfsziS9qEXAIWkJ9TvYulp4Vzv69i1ettTJDZTutkSolPphv7T6ekLlvZ2RM4/ZABycC9u4QgE+VA7lBZEy6ISDLSejYQIq9Mbs6nOtom5trmLmAGx6aawTZGtoB+OpyYIlI5WSybbBQMGob2fBWZdSNuql4dGMRwPmmb/uLFtbg7q8PUKwGWydg51NySCJJfRI+Qh21Z4kxIdZDMHwx/ZVxqSPY0uCayc+QPLgIqTMBStx/83eACAggzqt36tYAgB60VxRyB17pN2vrOWH3fkW0fe9UNDSNJe/0GSts66bdOJa3/5NPHr66I2fKAF0OXGUpt0LLSXY12OLY2tyK0N9wjNz+KbP1zLLVOf2Dc8H1VLwUupFoW/6GHkhFCVLm/6SK9sl37Cam/Znrtu8vr41rfg1LteUHOK1HqAjWtwFMQZXynpDDorLJOwdAFUEU7xqRc5ljZLYL4j4AH+luc="
  file: build/libs/*.jar
  file_glob: true
  on:
    repo: olemartin/chess-tournament
    tags: true
