language: java
jdk:
- oraclejdk8
script:
- ./gradlew shadowJar
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: "sR05eejKD9Mwq73de7OHMIW3YI7jehJByUPM75cnYzhQ4Uut7clGVraoscgu/Gsbn25z+fKJmJIm70hvFmCEVGYaPhI3wrOBftGMV97m4V40qAFtoWtISbaQsJhMX5+8Y7uVJiocxlgoAS6GWuoLRMsjeI0pNzv2ZPrApG+cuK/XkfJZGh2hBQKfscttFL82M3ee8wpJtFlksdKEXV7IeGdGl4aPsWV+PRJggxUzJTV+UREr5FAFzcGkkyuJ5F5q7PJmHrUzY6iMwBizHbsSgncFs4GWss1YXbAB8SJAm4MgGqeWtYlVZgrz38G655DsD9V9HIr3JfBnKmxdhFZ1Sdk29d3LbKQtPi/wza8uPI+tuJRu88fIr5R8aEfPWqEyjtbL7XllvoDJ8MQ0M2e7JKLC03qPHgrzYQcY/uXwRZhjoW7X8FOuzQpv62DOed8DLuw6vq1RBCS2Y264XgUsiwtPx+x4AEUv5Upfao+4fYFDlK/tfmofBYYw7ptehAtew7WFp+0KJri1mf2gKU8bFdG225zxTsra3IGriqETAD3bxp/6WxHo5cwEnz/V5DVn+mV0llYpoqf5oXFepnn8fORcaaH0EZSOLwQMCDHuH8qe5K1vKsFGYOe2pX0ar0TOj8lHjfF+CpoZgBA1XVgQPBJNRMO/WTcad9L0Fzshqu0="
  file: build/libs/*.jar
  file_glob: true
  on:
    repo: olemartin/chess-tournament
    tags: true
